# Generated by Django 2.1.5 on 2019-02-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
